# Generated by Django 3.1.7 on 2021-03-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(height_field=80, upload_to='img/', width_field=120),
        ),
    ]
