# Generated by Django 3.1.7 on 2021-03-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20210318_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
