# Generated by Django 3.1.7 on 2021-07-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_auto_20210704_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='date',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
