# Generated by Django 3.1.7 on 2021-07-04 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_auto_20210704_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 17, 2, 7, 749996)),
        ),
    ]
