# Generated by Django 3.1.7 on 2021-07-04 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_auto_20210704_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 23, 32, 29, 849640)),
        ),
    ]
