# Generated by Django 3.1.7 on 2021-07-04 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_auto_20210704_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 23, 33, 52, 73573)),
        ),
    ]
