# Generated by Django 3.1.7 on 2021-08-26 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_auto_20210704_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 0, 28, 56, 185809)),
        ),
    ]
