# Generated by Django 3.1.7 on 2021-08-27 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_auto_20210827_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='reserve',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 1, 29, 54, 941849)),
        ),
    ]
