# Generated by Django 3.1.7 on 2021-08-30 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_auto_20210831_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='input_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 1, 0, 24, 397019)),
        ),
    ]
